//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PERUN.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Military
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Military()
        {
            this.Awards = new HashSet<Awards>();
            this.DrivingLicense = new HashSet<DrivingLicense>();
            this.Education = new HashSet<Education>();
            this.Skills = new HashSet<Skills>();
            this.SportsCategory = new HashSet<SportsCategory>();
        }
    
        public int IDMilitary { get; set; }
        public string FirstName { get; set; }
        public string LastNAme { get; set; }
        public string Patronymic { get; set; }
        public int Age { get; set; }
        public int Height { get; set; }
        public int IDGender { get; set; }
        public Nullable<int> IDMilitaryUnit { get; set; }
        public string Address { get; set; }
        public Nullable<int> IDStatusOfAServiceman { get; set; }
        public Nullable<int> IDRank { get; set; }
        public string PlaceOfWork { get; set; }
        public string Passport { get; set; }
        public string Photo { get; set; }
    
        public virtual Gend Gend { get; set; }
        public virtual MilitaryUnit MilitaryUnit { get; set; }
        public virtual Rank Rank { get; set; }
        public virtual StatusOfServiceman StatusOfServiceman { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Awards> Awards { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DrivingLicense> DrivingLicense { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Education> Education { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Skills> Skills { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SportsCategory> SportsCategory { get; set; }
    }
}
